[tool.poetry]
name = "proteus"
version = "0.0.0"
description = "Logging, data connectors, monitoring, secret handling and general lifehacks to make data people lives easier."
authors = ["ECCO Sneaks & Data <esdsupport@ecco.com>"]
maintainers = ['GZU <gzu@ecco.com>', 'JRB <ext-jrb@ecco.com>']
license = 'Proprietary'
readme = "README.md"
repository = 'https://github.com/SneaksAndData/proteus'

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.26"
cryptography = "~36.0"
azure-identity = "~1.7"
deltalake = "<=0.5.6"
azure-storage-blob = ">12.7.0,<=12.10.0"
azure-mgmt-storage = "~19.1.0"
pandas = ">1.3,<1.5"

[tool.poetry.dev-dependencies]
pytest = "~6.2"
pytest-cov = "~2.12"
pylint = "~2.12"
requests = "~2.27"
cryptography = "~36.0"
pandas = "~1.4.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
