[tool.poetry]
name = "proteus"
version = "0.0.0"
description = "Logging, data connectors, monitoring, secret handling and general lifehacks to make data people lives easier."
authors = ["ECCO Sneaks & Data <esdsupport@ecco.com>"]
maintainers = ['GZU <gzu@ecco.com>', 'JRB <ext-jrb@ecco.com>']
license = 'Proprietary'
readme = "README.md"
repository = 'https://github.com/SneaksAndData/proteus'

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.group.identity.dependencies]
azure-identity = "~1.7"

[tool.poetry.group.beast.dependencies]
requests = "~2.27"
cryptography = "~36.0"

[tool.poetry.group.crystal.dependencies]
requests = "~2.27"

[tool.poetry.group.storage.dependencies]
deltalake = "~0.5"
azure-storage-blob = "~12.10.0"
azure-mgmt-storage = "~19.1.0"
pandas = "~1.4.1"

[tool.poetry.group.dev.dependencies]
pytest = "~6.2"
pytest-cov = "~2.12"
pylint = "~2.12"
requests = "~2.27"
cryptography = "~36.0"
pandas = "~1.4.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
