# Configuration for the Trino Iceberg connector

connector.name=iceberg
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=http://localhost:20001/catalog
iceberg.rest-catalog.warehouse=demo
iceberg.table-statistics-enabled=true
iceberg.extended-statistics.enabled=true
iceberg.extended-statistics.collect-on-write=true
iceberg.file-format=PARQUET
iceberg.compression-codec=ZSTD
iceberg.projection-pushdown-enabled=true


fs.native-s3.enabled=true
s3.region=us-east-1
s3.path-style-access=true
s3.endpoint=http://localhost:9000
s3.sts.endpoint=http://localhost:9000
s3.aws-access-key=minioadmin
s3.aws-secret-key=minioadmin

