name: Create development package

on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'create_package' && github.event.issue.state == 'open' }}
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.x'
          architecture: 'x64'
      - uses: actions/checkout@v3
        with:
          ref: refs/pull/${{github.event.issue.number}}/merge
          fetch-depth: 0
      - name: Install Poetry and dependencies
        uses: SneaksAndData/github-actions/install_poetry@remove-reliance-on-az-auth
        with:
          skip_dependencies: true
      - name: Create package
        uses: SneaksAndData/github-actions/create_package@remove-reliance-on-az-auth
        with:
          public_package_index_token: ${{ secrets.PYPI_API_TOKEN }}
          package_name: adapta
