name: Release to Azure Artifacts

on: workflow_dispatch
jobs:
  release_to_azure_artifacts:
    name: Release distribution to Azure Artifacts
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Install and Configure Poetry
        env:
          REPO_URL: ${{ secrets.AZOPS_PYPI_UPLOAD }}
        run: |
          set -e
          
          curl -sSL https://install.python-poetry.org | python3 - --preview
          
          poetry config repositories.azops $REPO_URL
      - name: Build Package and Publish distribution 📦 to Azure Artifacts
        env:
          POETRY_HTTP_BASIC_AZOPS_USERNAME: ${{ secrets.AZOPS_PAT_USER }}
          POETRY_HTTP_BASIC_AZOPS_PASSWORD: ${{ secrets.AZOPS_PAT }}
        run: |
          set -e
          
          version=$(git describe --tags --abbrev=7)
          sed -i "s/version = \"0.0.0\"/version = \"${version:1}\"/" pyproject.toml
          echo "__version__ = '${version:1}'" > ./proteus/_version.py
          
          poetry build && poetry publish -r azops
