name: Release to Azure Artifacts

on: workflow_dispatch
jobs:
  release_to_azure_artifacts:
    name: Release distribution to Azure Artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Install and Configure Poetry
        env:
          POETRY_HTTP_BASIC_AZOPS_USERNAME: ${{ secrets.AZOPS_PAT_USER }}
          POETRY_HTTP_BASIC_AZOPS_PASSWORD: ${{ secrets.AZOPS_PAT }}
        run: |
          set -e
          
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/1.1.13/get-poetry.py | python -
          . $HOME/.poetry/env
          echo "$(poetry --version)"
          
          poetry config repositories.azops https://pkgs.dev.azure.com/eccoSneaksAndData/_packaging/eccoSneaksAndData/pypi/simple/
      - name: Build Package and Publish distribution 📦 to Azure Artifacts
        if: startsWith(github.ref, 'refs/tags')
        run: |
          set -e
          
          version=$(git describe --tags --abbrev=7)
          
          sed -i "s/version = \"0.0.0\"/version = \"$version\"/" pyproject.toml
          
          poetry package && poetry publish -r azops
