name: Run unit tests

on:
  pull_request:
    branches: [ main ]

jobs:
  validate_code:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Don't cancel other versions if one fails
      matrix:
        python-version: [ "3.11", "3.12", "3.13", "3.14" ]

    permissions:
      contents: read
      id-token: write
      pull-requests: write

    if: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install

      - name: Prepare environment
        run: uv sync --frozen --all-extras

      - name: Build the Docker Compose stack
        run: docker compose up --quiet-pull -d

      - name: Get Compose Logs
        if: always()
        run: docker compose logs

      - name: Run Tests
        run:  |
          set -euo pipefail
          
          sleep 10 # let Trino boot
          
          uv run pytest | tee pytest-coverage.txt

      - name: Publish Code Coverage
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt